# Generated by Django 5.0.10 on 2026-04-10 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('transaction_date', models.DateField()),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='office_sim.officerole')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOfficeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='office_sim.officerole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='office_docs/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='office_sim.officetransaction')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTransactionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_progress', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='office_sim.officetransaction')),
            ],
            options={
                'unique_together': {('student', 'transaction')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100)),
                ('expected_output', models.CharField(blank=True, max_length=200)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='office_sim.officetransaction')),
            ],
            options={
                'ordering': ['step_no'],
                'unique_together': {('transaction', 'step_no')},
            },
        ),
    ]
