# Generated by Django 5.0.10 on 2026-04-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('process', 'Process'), ('decision', 'Decision'), ('end', 'End')], default='process', max_length=20)),
                ('position', models.PositiveIntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='office_sim.officetransaction')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('transaction', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('position', models.PositiveIntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='office_sim.officetransaction')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='office_sim.workflownode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='office_sim.workflownode')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
