# Generated by Django 5.0.10 on 2026-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0002_workflownode_workflowconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerole',
            name='office_display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
