# Generated by Django 5.0.10 on 2026-04-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0003_officerole_office_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='lane',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant_clerk', 'Accountant Clerk'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('supplier', 'Supplier')], default='admin', max_length=50),
        ),
    ]
