# Generated by Django 5.0.10 on 2026-04-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0004_workflowstep_lane'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='node_type',
            field=models.CharField(choices=[('start', 'Start'), ('process', 'Process'), ('decision', 'Decision'), ('end', 'End')], default='process', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='office_sim.officerole'),
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='lane',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='responsible_person',
        ),
    ]
