# Generated by Django 5.0.10 on 2026-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0005_alter_workflowstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflownode',
            options={'ordering': ['row', 'id']},
        ),
        migrations.RenameField(
            model_name='workflownode',
            old_name='position',
            new_name='row',
        ),
        migrations.AddField(
            model_name='officerole',
            name='contract_text_so',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officerole',
            name='job_description_so',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='lane',
            field=models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Accounting Clerk'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('supplier', 'Supplier')], default='clerk', max_length=50),
        ),
    ]
