# Generated by Django 5.0.10 on 2026-04-17 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0005_alter_workflowstep_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflownode',
            options={'ordering': ['row', 'id']},
        ),
        migrations.RenameField(
            model_name='workflownode',
            old_name='position',
            new_name='row',
        ),
        migrations.AddField(
            model_name='officerole',
            name='contract_text_so',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officerole',
            name='job_description_so',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='lane',
            field=models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Accounting Clerk'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('supplier', 'Supplier')], default='clerk', max_length=50),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='expected_output',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='office_sim.officerole'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('transaction', 'step_no')},
        ),
    ]
