# Generated by Django 5.0.10 on 2026-04-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_sim', '0006_alter_workflownode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='lane',
            field=models.CharField(choices=[('admin', 'Admin'), ('clerk', 'Accounting Clerk'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('supplier', 'Supplier')], default='clerk', max_length=50),
        ),
    ]
