# Generated by Django 5.0.10 on 2026-04-05 01:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('STRUCT', 'Structured Question'), ('SEQ', 'Sequencing')], default='MCQ', max_length=10)),
                ('points', models.PositiveIntegerField(default=2)),
                ('correct_part_a', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_part_b', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_part_c', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, default='Beginner', max_length=50)),
                ('overview', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True, help_text='One per line')),
                ('topics_covered', models.TextField(blank=True, help_text='One per line')),
                ('assessment_format', models.TextField(blank=True)),
                ('exam_structure', models.TextField(blank=True)),
                ('preparation_tips', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True, help_text='One per line')),
                ('study_materials', models.TextField(blank=True, help_text='One per line')),
            ],
        ),
        migrations.CreateModel(
            name='BankChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.bankquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('use_question_bank', models.BooleanField(default=True)),
                ('question_count', models.PositiveIntegerField(default=50)),
                ('created_by', models.ForeignKey(blank=True, help_text='Teacher who created/owns this exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('STRUCT', 'Structured Question'), ('SEQ', 'Sequencing')], default='MCQ', max_length=10)),
                ('points', models.PositiveIntegerField(default=2)),
                ('correct_part_a', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_part_b', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_part_c', models.CharField(blank=True, max_length=150, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('structured_part_a', models.CharField(blank=True, max_length=150, null=True)),
                ('structured_part_b', models.CharField(blank=True, max_length=150, null=True)),
                ('structured_part_c', models.CharField(blank=True, max_length=150, null=True)),
                ('sequencing_answer', models.JSONField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt')),
                ('selected_bank_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.bankchoice')),
                ('bank_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.bankquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.choice')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct_order', models.PositiveIntegerField()),
                ('bank_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_items', to='exams.bankquestion')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_items', to='exams.question')),
            ],
            options={
                'ordering': ['correct_order'],
            },
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='exams.subject'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exams.attempt')),
                ('bank_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.bankquestion')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('attempt', 'bank_question')},
            },
        ),
        migrations.CreateModel(
            name='ExamResitPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_attempts', models.PositiveIntegerField(default=0)),
                ('can_view', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_permissions', to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'user'], name='exams_examr_exam_id_8491ae_idx')],
                'unique_together': {('exam', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('attempt', 'question'), name='unique_attempt_exam_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_question__isnull', False)), fields=('attempt', 'bank_question'), name='unique_attempt_bank_question'),
        ),
    ]
