# Generated by Django 5.0.10 on 2026-01-22 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_attempt_options_alter_attempt_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresitpermission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_permissions', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examresitpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resit_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='exams_answe_attempt_62aa9a_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'exam'], name='exams_attem_user_id_028ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam'], name='exams_attem_exam_id_92f0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['submitted_at'], name='exams_attem_submitt_bc45e0_idx'),
        ),
        migrations.AddIndex(
            model_name='examresitpermission',
            index=models.Index(fields=['exam', 'user'], name='exams_examr_exam_id_8491ae_idx'),
        ),
    ]
