# Generated by Django 5.0.10 on 2026-01-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_examresitpermission_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresitpermission',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
    ]
