# Generated by Django 5.0.10 on 2026-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examresitpermission_can_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresitpermission',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
