# Generated by Django 5.0.10 on 2026-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_examresitpermission_can_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
