# Generated by Django 5.0.10 on 2026-02-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attempt',
            name='exams_attem_user_id_028ad0_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='exams_attem_exam_id_92f0cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='attempt',
            name='exams_attem_submitt_bc45e0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together=set(),
        ),
    ]
