# Generated by Django 5.0.10 on 2026-02-20 16:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_attempt_exams_attem_user_id_028ad0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BankChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('STRUCT', 'Structured Question')], default='MCQ', max_length=10)),
                ('correct_part_a', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_part_b', models.CharField(blank=True, max_length=150, null=True)),
                ('correct_part_c', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, default='Beginner', max_length=50)),
                ('overview', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True, help_text='One per line')),
                ('topics_covered', models.TextField(blank=True, help_text='One per line')),
                ('assessment_format', models.TextField(blank=True)),
                ('exam_structure', models.TextField(blank=True)),
                ('preparation_tips', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True, help_text='One per line')),
                ('study_materials', models.TextField(blank=True, help_text='One per line')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='exams_answe_attempt_62aa9a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='structured_part_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='structured_part_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='structured_part_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_count',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='use_question_bank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_part_a',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_part_b',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_part_c',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('STRUCT', 'Structured Question')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='exams.attempt'),
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_bank_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.bankchoice'),
        ),
        migrations.AddField(
            model_name='bankchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.bankquestion'),
        ),
        migrations.AddField(
            model_name='attemptquestion',
            name='bank_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.bankquestion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='bank_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.bankquestion'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('attempt', 'question'), name='unique_attempt_exam_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_question__isnull', False)), fields=('attempt', 'bank_question'), name='unique_attempt_bank_question'),
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='exams.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attemptquestion',
            unique_together={('attempt', 'bank_question')},
        ),
    ]
