# Generated by Django 5.0.10 on 2026-04-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_attemptquestion_bankchoice_bankquestion_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
