# Generated by Django 5.0.10 on 2026-04-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='sequencing_answer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankquestion',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('STRUCT', 'Structured Question'), ('SEQ', 'Sequencing')], default='MCQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('STRUCT', 'Structured Question'), ('SEQ', 'Sequencing')], default='MCQ', max_length=10),
        ),
        migrations.CreateModel(
            name='SequencingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct_order', models.PositiveIntegerField()),
                ('bank_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_items', to='exams.bankquestion')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_items', to='exams.question')),
            ],
            options={
                'ordering': ['correct_order'],
            },
        ),
    ]
