# Generated by Django 5.0.10 on 2026-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('exams', '0010_attemptquestion_bankchoice_bankquestion_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_students_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['allow_students_view'], name='courses_cou_allow_s_59c0ad_idx'),
        ),
    ]
