# Generated by Django 5.0.10 on 2026-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaccess',
            name='lessons_can_view',
            field=models.BooleanField(default=True),
        ),
    ]
