# Generated by Django 5.0.10 on 2026-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_fix_old_lessons_visibility'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lessonquizquestion',
            name='uniq_question_order_per_quiz',
        ),
        migrations.RemoveIndex(
            model_name='lessonquizquestion',
            name='courses_les_quiz_id_b7f5db_idx',
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True / False')], default='MCQ', max_length=10),
        ),
    ]
