# Generated by Django 5.0.10 on 2026-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseaccess'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='uniq_lesson_order_per_course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='allow_students_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['allow_students_view'], name='courses_les_allow_s_45af35_idx'),
        ),
    ]
