# Generated by Django 5.0.10 on 2026-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lessonquizquestion_uniq_question_order_per_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonquizanswer',
            name='awarded_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessonquizanswer',
            name='text_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='expected_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
        migrations.AddField(
            model_name='lessonquizquestion',
            name='marking_guide',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lessonquizquestion',
            name='qtype',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True / False'), ('STRUCT', 'Structured')], default='MCQ', max_length=10),
        ),
    ]
