# Generated by Django 5.0.10 on 2026-02-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseaccess_lessons_can_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='allow_students_view',
            field=models.BooleanField(default=False, verbose_name='Allow Students View'),
        ),
    ]
