# Generated by Django 5.0.10 on 2026-02-23 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_allow_students_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'chapter__order', 'order', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_is_publ_4b99b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_created_51cadc_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cou_allow_s_59c0ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='courses_les_course__dc0bc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='courses_les_is_publ_ebf633_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='courses_les_allow_s_45af35_idx',
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.chapter'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='uniq_chapter_order_per_course'),
        ),
    ]
