# Generated by Django 5.0.10 on 2026-02-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_chapter_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='chapter',
            name='uniq_chapter_order_per_course',
        ),
    ]
